amzstorefront/models.py
from amzstorefront import app
from flask_sqlalchemy import SQLAlchemy
from flask.ext.login import UserMixin
from sqlalchemy import func
from werkzeug import cached_property
from utils import *
import datetime


__all__ = ('db', 'User', 'Category', 'Product')


db = SQLAlchemy(app)


class User(UserMixin):
    def __init__(self):
        self.id = 'admin'


class Category(db.Model):
    __tablename__ = 'categories'

    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, default=func.now())
    name = db.Column(db.String)
    slug = db.Column(db.String)
    description = db.Column(db.String)
    position = db.Column(db.Integer, default=0, nullable=False)

    products = db.relationship('Product', backref='category')

    @classmethod
    def find(cls, id):
        return Category.query.filter_by(id=id).first()

    @classmethod
    def find_by_slug(cls, slug):
        return Category.query.filter_by(slug=slug).first()

    @classmethod
    def find_by_name(cls, name):
        return Category.query.filter_by(name=name).first()

    def __init__(self, name=None):
        if not name is None:
            self.name = name
            self.slug = name.lower()

    def __repr__(self):
        return self.name


class Product(db.Model):
    __tablename__ = 'products'

    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, default=func.now())
    last_refreshed_at = db.Column(db.DateTime)
    ASIN = db.Column(db.String)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'))
    parent_id = db.Column(db.Integer, db.ForeignKey('products.id'))
    name = db.Column(db.String)
    slug = db.Column(db.String)
    brand = db.Column(db.String)
    description = db.Column(db.String)
    price = db.Column(db.Float)
    currency = db.Column(db.String)
    availability = db.Column(db.String)
    details_url = db.Column(db.String)
    reviews_url = db.Column(db.String)
    image_url = db.Column(db.String)
    thumb_url = db.Column(db.String)
    has_reviews = db.Column(db.Boolean, default=False, nullable=False)
    formated_price = db.Column(db.String)
    out_of_stock = db.Column(db.Boolean, default=False, nullable=False)
    visible = db.Column(db.Boolean, default=False, nullable=False)
    overrided_fields = db.Column(db.PickleType)
    variation_attrs = db.Column(db.PickleType)
    variation_dimensions = db.Column(db.PickleType)
    variation_main_dimension = db.Column(db.String)
    editor_comment = db.Column(db.String)
    video_review_url = db.Column(db.String)
    video_review_html = db.Column(db.String)
    video_review_author = db.Column(db.String)
    video_review_author_url = db.Column(db.String)
    featured = db.Column(db.Boolean, default=False)

    parent = db.relationship('Product', backref='variations', remote_side=[id], cascade='all')

    @classmethod
    def find(cls, id):
        return Product.query.filter_by(id=id).first()

    @classmethod
    def find_by_asin(cls, ASIN):
        return Product.query.filter_by(ASIN=ASIN).first()

    def __init__(self, ASIN=None):
        self.ASIN = ASIN
        self.overrided_fields = set()

    def __repr__(self):
        return "#%s %s" % (self.ASIN, self.fullname)

    @property
    def fullname(self):
        if self.brand:
            return self.brand + ' ' + self.name
        return self.name

    @property
    def parent_or_self(self):
        if self.parent:
            return self.parent
        return self

    @cached_property
    def formated_last_refreshed_at(self):
        if not self.last_refreshed_at:
            return 'a long time ago'
        delta = datetime.datetime.now() - self.last_refreshed_at
        if delta.seconds < 300:
            return 'less than 5 minutes ago'
        if delta.seconds < 3600:
            return 'less than an hour ago'
        return '%d hours ago' % (delta.seconds / 60 / 60)

    def get_variation(self, ASIN):
        for v in self.variations:
            if v.ASIN == ASIN:
                return v
        return None

    @cached_property
    def variation_matrix(self):
        if not self.variation_main_dimension or not self.variation_dimensions or len(self.variation_dimensions) <= 1:
            return self.variations

        matrix = {}
        one_per_dimension = True
        for v in self.variations:
            dim_name = v.variation_attrs[self.variation_main_dimension]
            if not dim_name in matrix:
                matrix[dim_name] = []
            else:
                one_per_dimension = False
            matrix[dim_name].append(v)

        if one_per_dimension:
            return self.variations
        if len(matrix) == 1:
            return matrix.values()[0]
        return matrix

    @cached_property
    def variation_name(self):
        return ", ".join(map(str, self.variation_attrs.values()))

    @cached_property
    def formated_variation_dimensions(self):
        if not self.variation_dimensions:
            return None
        names = {"Size": "sizes", "ClothingSize": "sizes", "Color": "colors", "MaterialType": "types of material",
                 "MetalType": "types of metal", "OperatingSystem": "operating systems", "Model": "models"}
        dim_names = [names[d] for d in self.variation_dimensions if d in names]
        if len(dim_names) == 0:
            return None
        if len(dim_names) > 1:
            last = dim_names.pop(-1)
            formated_dim_names = "%s and %s" % (", ".join(dim_names), last)
        else:
            formated_dim_names = dim_names[0]
        return "Available in multiple %s" % formated_dim_names

    def build_variation_name(self, exclude_dimension=None):
        values = [str(v) for k, v in self.variation_attrs.items() if k != exclude_dimension]
        return ", ".join(values)

    def is_field_overrided(self, field):
        if self.overrided_fields is None:
            return False
        return field in self.overrided_fields

    def fetch_video_review_from_url(self, url):
        r = oembed_consumer.embed(url, maxwidth=610)
        self.video_review_url = url
        self.video_review_html = r['html']
        self.video_review_author = r['author_name']
        self.video_review_author_url = r['author_url']

amzstorefront/__init__.py
from flask import Flask
import os


__all__ = ['app']


app = Flask(__name__)
app.config['ENV'] = os.environ.get('FLASK_ENV', 'prod')
app.config.from_object('amzstorefront.settings.%sConfig' % app.config['ENV'].capitalize())


import views

amzstorefront/views/__init__.py
from flask import render_template, request, flash, redirect, url_for
from flask.ext import wtf
from flask.ext import login
from amzstorefront import app
from amzstorefront.models import *
import admin
import store


app.register_blueprint(store.blueprint)
admin.create_admin(app)


def register_page(endpoint, template_filename):
    def render_page():
        return render_template(template_filename)
    app.add_url_rule(endpoint, endpoint.strip('/').replace('/', '_'), render_page)

register_page('/about', 'pages/about.html')
register_page('/contact', 'pages/contact.html')
register_page('/affiliates', 'pages/affiliates.html')


login_manager = login.LoginManager()
login_manager.login_view = "user_login"
login_manager.setup_app(app)


@login_manager.user_loader
def load_user(id):
    return User()


class LoginForm(wtf.Form):
    username = wtf.TextField(validators=[wtf.required()])
    password = wtf.PasswordField(validators=[wtf.required()])


@app.route('/login', methods=('GET', 'POST'))
def user_login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        if form.username.data == app.config['ADMIN_USERNAME'] and form.password.data == app.config['ADMIN_PASSWORD']:
            login.login_user(User())
            return redirect(url_for('admin.index'))
        else:
            flash('Invalid username or password', 'error')

    return render_template('login.html', form=form)


@app.route('/logout')
def logout():
    login.logout_user()
    return redirect(url_for('store.home'))

amzstorefront/views/admin.py
from flask.ext.admin import Admin, AdminIndexView, BaseView, expose
from flask.ext.admin.contrib.sqlamodel import ModelView
from flask.ext.admin.contrib.fileadmin import FileAdmin
from flask.ext import wtf
from flask.ext.login import current_user
from amzstorefront.models import *
import os


class AuthenticatedView(object):
    def is_accessible(self):
        return current_user.is_authenticated()


class IndexView(AuthenticatedView, AdminIndexView):
    pass


class ProductsView(AuthenticatedView, ModelView):

    column_list = ('ASIN', 'brand', 'name', 'formated_price', 'visible')
    column_sortable_list = ('id', 'brand', 'name')
    column_searchable_list = ('ASIN', 'brand', 'name')

    form_columns = ('ASIN', 'visible', 'category', 'name', 'slug', 'brand', 'name', 'description', 'image_url', 'thumb_url', 'editor_comment', 'video_review_url', 'video_review_html', 'video_review_author', 'video_review_author_url')
    form_overrides = dict(description=wtf.TextAreaField, editor_comment=wtf.TextAreaField, video_review_html=wtf.TextAreaField)
    form_args = dict(ASIN=dict(validators=[wtf.required()]))

    def __init__(self, session, **kwargs):
        super(ProductsView, self).__init__(Product, session, **kwargs)

    def get_query(self):
        return self.session.query(self.model).filter(Product.parent_id==None)


class CategoriesView(AuthenticatedView, ModelView):

    column_list = ('name', 'slug')
    form_columns = ('name', 'slug', 'description', 'position')
    form_overrides = dict(description=wtf.TextAreaField)
    form_args = dict(name=dict(validators=[wtf.required()]), slug=dict(validators=[wtf.required()]))

    def __init__(self, session, **kwargs):
        super(CategoriesView, self).__init__(Category, session, **kwargs)


class TemplatesView(AuthenticatedView, FileAdmin):
    def __init__(self):
        path = os.path.join(os.path.dirname(__file__), '..', 'templates')
        super(TemplatesView, self).__init__(path, '/templates/', name='Templates')


class AssetsView(AuthenticatedView, FileAdmin):
    def __init__(self):
        path = os.path.join(os.path.dirname(__file__), '..', 'static')
        super(AssetsView, self).__init__(path, '/static/', name='Assets')


def create_admin(app):
    admin = Admin(app, name='Admin', index_view=IndexView())
    admin.add_view(CategoriesView(db.session))
    admin.add_view(ProductsView(db.session))
    admin.add_view(TemplatesView())
    admin.add_view(AssetsView())

amzstorefront/views/store.py
from flask import Blueprint, current_app, render_template, request, g, session, jsonify, abort, redirect, url_for
from amzstorefront.models import *
from amzstorefront.utils import *
from amzstorefront.amazon import Cart, InvalidCartItem
import time


blueprint = Blueprint('store', __name__)


@blueprint.before_request
def setup_request_globals():
    if 'cart_id' in session and 'cart_hmac' in session:
        g.cart = Cart.load(session['cart_id'], session['cart_hmac'], session.get('cart_assoc_tag'))
    else:
        g.cart = Cart()

    if 'afftag' in session and session['afftag_expiry'] < time.time():
        del(session['afftag'])
        del(session['afftag_expiry'])
        if not g.cart.created:
            session.permanent = False
            
    g.categories = Category.query.all()


@blueprint.after_request
def save_cart_after_request(response):
    if g.cart.created and g.cart.modified:
        session['cart_id'] = g.cart.id
        session['cart_hmac'] = g.cart.hmac
        session['cart_assoc_tag'] = g.cart.assoc_tag
        g.cart.persist(current_app.config['CART_TTL'])
    return response


@blueprint.route('/')
def home():
    return redirect(url_for('.all_products'))
    return render_template('store/index.html')


@blueprint.route('/all')
def all_products():
    products = Product.query.filter_by(parent_id=None).all()
    return render_template('store/product_list_page.html', list_title='All categories', 
        products=products)


@blueprint.route('/<slug>')
def show_category(slug):
    category = Category.find_by_slug(slug)
    if not category:
        return abort(404)
    g.active_category_id = category.id
    return render_template('store/product_list_page.html', list_title=category.name, 
            list_description=category.description, products=category.products)


@blueprint.route('/p/<int:product_id>-<slug>')
def show_product(product_id, slug):
    product = Product.find(product_id)
    if not product:
        return abort(404)

    if current_app.config['ALLOW_AFFILIATES'] and 'afftag' in request.args:
        allowed_tags = current_app.config['ALLOWED_AFFILIATE_TAGS']
        if allowed_tags is None or request.args['afftag'] in allowed_tags:
            session['afftag'] = request.args['afftag']
            session['afftag_expiry'] = time.time() + current_app.config['AFFILIATE_TAG_TTL']
            session.permanent = True

    g.active_category_id = product.category_id
    return render_template('store/product.html', product=product)


@blueprint.route('/cart')
def get_cart():
    return render_template('store/cart.html')


@blueprint.route('/cart/add', methods=['POST'])
def add_to_cart():
    product = Product.find(request.form['id'])
    if not product:
        return abort(404)

    if not g.cart.created and 'afftag' in session:
        g.cart.assoc_tag = session['afftag']

    try:
        g.cart.add_product(product)
    except InvalidCartItem as e:
        current_app.logger.debug(e)
        return abort(400)
    except Exception as e:
        current_app.logger.error(e)
        return abort(500)

    session.permanent = True
    return render_template('store/cart.html')


@blueprint.route('/cart/update/<item_id>', methods=['POST'])
def update_cart_item(item_id):
    quantity = request.form['quantity']
    if quantity == '':
        quantity = 0
    elif not quantity.isdigit():
        return abort(400)
    g.cart.update_item(item_id, int(quantity))
    return render_template('store/cart.html')


@blueprint.route('/cart/checkout')
def checkout():
    g.cart.refresh()
    if not g.cart.created:
        return redirect(url_for('.home'))
    return redirect(g.cart.purchase_url)

amzstorefront/templates/flash_messages.html
<div id="flash-messages">
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                <a class="close" data-dismiss="alert">×</a>
                {{ message }}
            </div>
        {% endfor %}
    {% endwith %}
  </div>

amzstorefront/templates/helpers.html
{% macro form_field(field) -%}
    <div class="control-group {% if field.errors %}error{% endif %}">
        {% if field.type != 'BooleanField' %}
            <label for="{{ field.id }}" class="control-label">
                {{ field.label.text }}{% if field.flags.required %} *{% endif %}:
            </label>
        {% endif %}
        <div class="controls">
            {% set class_ = kwargs.pop('class_', '') %}
            {% if field.flags.required %}
                {% set class_ = class_ + ' required' %}
            {% endif %}
            {% if field.type == 'BooleanField' %}
                <label class="checkbox">
                    {{ field(class_=class_, **kwargs) }}
                    {{ field.label.text }}
                </label>
            {% else %}
                {% if field.type in ('TextField', 'TextAreaField', 'MarkdownField') %}
                    {% set class_ = class_ + ' input-xlarge span5' %}
                {% elif field.type == 'FileField' %}
                    {% set class_ = class_ + ' input-file' %}
                {% endif %}
                {{ field(class_=class_, **kwargs) }}
            {% endif %}
            {% if field.errors %}
                <span class="error help-inline">{{ field.errors|join(', ') }}</span>
            {% endif %}
            {% if field.description %}
                <p class="help-block">{{ field.description|safe }}</p>
            {% endif %}
        </div>
    </div>
{%- endmacro %}

amzstorefront/templates/layout.html
<!doctype html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>{% block title %}Amazon Storefront{% endblock %}</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href='http://fonts.googleapis.com/css?family=Rambla' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendors/bootstrap/css/bootstrap.min.css') }}" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendors/bootstrap/css/bootstrap-responsive.min.css') }}" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/layout.css') }}" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/store.css') }}" />

  <script type="text/javascript" src="{{ url_for('static', filename='vendors/jquery-1.8.3.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='vendors/bootstrap/js/bootstrap.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/common.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/store.js') }}"></script>

  {% block head %}{% endblock %}
</head>
<body data-spy="scroll" data-target="#topbar">
  <header id="header">
    <div class="container">
      <h1><a href="{{ url_for('store.home') }}">Amazon Storefront</a></h1>
      <div id="cart">
        <div class="status">
          <i class="icon icon-shopping-cart"></i> Loading cart...
        </div>
      </div>
    </div>
  </header>
  {% include "menu.html" %}
  <div id="main" class="container">
    {% block main %}
      {% include "flash_messages.html" %}
      {% block content %}{% endblock %}
    {% endblock %}
  </div>
  <footer id="footer">
    <div class="container">
      <p>
        &copy; Amazon Storefront 2013.
      </p>
      <p>
        Amazon and the Amazon logo are trademarks of Amazon.com, Inc. or its affiliates.<br>
        Certain content that appears on this website comes from Amazon this content is provided 'as is' and is subject to change or removal at any time.
      </p>
      {% if config.get('DEBUG') or request.args.get('debug') == '1' %}
        <p>
          DEBUG { {% if g.cart and g.cart.created %}CartId: {{ g.cart.id }} | CartHMAC: {{ g.cart.hmac }} | CartAssocTag: {{ g.cart.assoc_tag }} |{% endif %}
          {% if product %}ProductId: {{ product.id }} | ProductASIN: {{ product.ASIN }} |{% endif %} }
        </p>
      {% endif %}
    </div>
  </footer>
  <div id="cart-overlay"></div>
</body>
</html>

amzstorefront/templates/layout_with_sidebar.html
{% extends "layout.html" %}
{% block main %}
  <div class="row-fluid">
    <div id="content" class="span9">
      {% include "flash_messages.html" %}
      {% block content %}{% endblock %}
    </div>
    <div id="sidebar" class="span3">
      {% block sidebar %}{% endblock %}
    </div>
  </div>
{% endblock %}

amzstorefront/templates/login.html
{% extends "layout.html" %}
{% from 'helpers.html' import form_field %}
{% block content %}
  <form action="{{ url_for('.user_login') }}" method="post">
    {{ form.csrf_token }}
    {{ form_field(form.username) }}
    {{ form_field(form.password) }}
    <div class="form-actions">
      <input type="submit" value="Login" class="btn btn-primary" />
    </div>
  </form>
{% endblock %}

amzstorefront/templates/menu.html
<div id="menu" class="navbar navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="{% if request.endpoint == 'store.all_products' %}active{% endif %}">
            <a href="{{ url_for('store.all_products') }}">All</a>
          </li>
          {% for category in g.categories %}
            <li class="{% if g.active_category_id == category.id %}active{% endif %}">
              <a href="{{ url_for('store.show_category', slug=category.slug) }}">{{ category.name }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>